"""
This file was almost entirely generated by Github Copilot.
Main prompt: create a GUI for the Snake game using Pygame (attached is snake_gym.py).
"""
import pygame
import sys
import time
import random
from snake_gym import SnakeEnv

game = SnakeEnv()

GRID_SIZE = game.grid_size
CELL_SIZE = 40
GRID_WIDTH = GRID_SIZE * CELL_SIZE
CONSOLE_WIDTH = 400 
WIDTH = GRID_WIDTH + CONSOLE_WIDTH 
HEIGHT = GRID_WIDTH 

# Action names
ACTION_NAMES = {0: 'UP', 1: 'RIGHT', 2: 'DOWN', 3: 'LEFT'} 

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0) # Snake body
DARK_GREEN = (0, 180, 0) # Snake head
RED = (255, 0, 0)   # Apple
ORANGE = (255, 165, 0) # Orange
YELLOW = (255, 255, 0) # Banana
GRAY = (200, 200, 200) # Console background


# Setup display
screen=None

game_ended = False
action_results = []

fps = 60
sleeptime = 0.1
clock = None

def setup(GUI=True):
    global screen, clock
    if GUI:
        pygame.init()
        screen = pygame.display.set_mode((WIDTH, HEIGHT))
        pygame.display.set_caption('Snake Game')
        clock = pygame.time.Clock()

def reset_game_state():
    """Reset the GUI state when starting a new episode"""
    global game_ended, action_results
    game_ended = False
    action_results = []

def draw_grid():
    for x in range(0, GRID_WIDTH, CELL_SIZE):
        for y in range(0, HEIGHT, CELL_SIZE):
            rect = pygame.Rect(x, y, CELL_SIZE, CELL_SIZE)
            pygame.draw.rect(screen, BLACK, rect, 1)

    rect = pygame.Rect(GRID_WIDTH, 0, CONSOLE_WIDTH, HEIGHT)
    pygame.draw.rect(screen, GRAY, rect)

def draw_snake(snake):
    for i, segment in enumerate(snake):
        x, y = segment
        rect = pygame.Rect(x * CELL_SIZE, y * CELL_SIZE, CELL_SIZE, CELL_SIZE)
        # Draw head in light green, body in dark green
        color = GREEN if i == 0 else DARK_GREEN
        pygame.draw.rect(screen, color, rect)

def draw_food(food_positions):
    for food_type, position in food_positions.items():
        if position is not None:
            x, y = position
            rect = pygame.Rect(x * CELL_SIZE, y * CELL_SIZE, CELL_SIZE, CELL_SIZE)
            if food_type == 'apple':
                pygame.draw.rect(screen, RED, rect)
            elif food_type == 'orange':
                pygame.draw.rect(screen, ORANGE, rect)
            elif food_type == 'banana':
                pygame.draw.rect(screen, YELLOW, rect)

def draw_console(score, action_results, game_ended=False):
    font = pygame.font.SysFont(None, 24)
    y_offset = 10

    score_text = font.render(f'Score: {score}', True, BLACK)
    screen.blit(score_text, (GRID_WIDTH + 10, y_offset))
    y_offset += 25
    
    apple_text = font.render('Apple: 10 pts', True, RED)
    screen.blit(apple_text, (GRID_WIDTH + 10, y_offset))
    y_offset += 18
    
    orange_text = font.render('Orange: 40 pts', True, ORANGE)
    screen.blit(orange_text, (GRID_WIDTH + 10, y_offset))
    y_offset += 18
    
    banana_text = font.render('Banana: 100 pts', True, YELLOW)
    screen.blit(banana_text, (GRID_WIDTH + 10, y_offset))
    y_offset += 25

    for result in action_results[-10:]:
        # Convert action number to name if it's an integer
        action = result.get('action', '')
        if isinstance(action, int):
            action = ACTION_NAMES.get(action, action)
        
        reward = result.get('reward', 0)
        done = result.get('done', False)
        
        # Format: action: UP, reward: 10, done: False
        result_text = font.render(f"action: {action}, reward: {reward}, done: {done}", True, BLACK)
        screen.blit(result_text, (GRID_WIDTH + 10, y_offset))
        y_offset += 18
    
    # Display game over message in console
    if game_ended:
        y_offset += 15
        game_over_font = pygame.font.SysFont(None, 32)
        game_over_text = game_over_font.render('GAME OVER!', True, RED)
        screen.blit(game_over_text, (GRID_WIDTH + 10, y_offset))
        y_offset += 35
        final_score_text = font.render(f'Final Score: {score}', True, BLACK)
        screen.blit(final_score_text, (GRID_WIDTH + 10, y_offset))
        y_offset += 25
        restart_text = font.render('Press R to Restart', True, BLACK)
        screen.blit(restart_text, (GRID_WIDTH + 10, y_offset))

def main():
    global game_ended, action_results
    setup(GUI=True)
    running = True

    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if game_ended and event.key == pygame.K_r:
                    game.reset()
                    game_ended = False
                    action_results = []
                elif not game_ended:
                    if event.key == pygame.K_UP:
                        action = 0
                    elif event.key == pygame.K_RIGHT:
                        action = 1
                    elif event.key == pygame.K_DOWN:
                        action = 2
                    elif event.key == pygame.K_LEFT:
                        action = 3
                    else:
                        action = None

                    if action is not None:
                        observation, reward, done, info = game.step(action)
                        action_results.append({
                            'action': action,
                            'reward': reward,
                            'done': done,
                            'info': info
                        })
                        if done:
                            game_ended = True

        screen.fill(WHITE)
        draw_grid()
        draw_snake(game.snake)
        draw_food(game.food_positions)
        draw_console(game.score, action_results, game_ended)

        pygame.display.flip()
        clock.tick(fps)

def refresh(action, reward, done, info, delay=0.1):
    global game_ended, action_results
    action_results.append({
        'action': action,
        'reward': reward,
        'done': done,
        'info': info
    })
    if done:
        game_ended = True

    if screen:
        screen.fill(WHITE)
        draw_grid()
        draw_snake(game.snake)
        draw_food(game.food_positions)
        draw_console(game.score, action_results, game_ended)

        pygame.display.flip()
        clock.tick(fps)
        time.sleep(delay)

if __name__ == "__main__":
    setup()
    main()